language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: ENABLEDEBUG=true
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
      env: VISHIDDEN=true
    - os: osx
      osx_image: xcode11.3
      env: OSX=10.14 VISHIDDEN=true
      compiler: clang
    - os: osx
      osx_image: xcode10.1
      env: OSX=10.13 ENABLEDEBUG=true
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      env: OSX=10.13
      compiler: clang

before_script:
  - export VISHIDDEN=${VISHIDDEN:-false}
  - export ENABLEDEBUG=${ENABLEDEBUG:-false}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash gcc; export CC=gcc-9 ; export CXX=g++-9 ; $CC --version; $CXX --version; gfortran --version; fi

script:
  - git clone --depth 1 https://github.com/coin-or-tools/ThirdParty-ASL
  - git clone --depth 1 https://github.com/coin-or-tools/ThirdParty-Metis
  - git clone --depth 1 https://github.com/coin-or-tools/ThirdParty-Mumps
  - git clone --depth 1 https://github.com/coin-or/CoinUtils
  - git clone --depth 1 https://github.com/coin-or/Osi
  - git clone --depth 1 https://github.com/coin-or/Clp
  - git clone --depth 1 https://github.com/coin-or/Cgl
  - git clone --depth 1 https://github.com/coin-or/Cbc
  - git clone --depth 1 https://github.com/coin-or/Ipopt
  - git clone --depth 1 --branch autotools-update https://github.com/coin-or/Bonmin
  - pushd ThirdParty-ASL && ./get.ASL && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd ThirdParty-Metis && ./get.Metis && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd ThirdParty-Mumps && ./get.Mumps && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd CoinUtils/CoinUtils && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Osi/Osi && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Clp/Clp && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Cgl/Cgl && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Cbc/Cbc && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Ipopt && ./configure --prefix=$HOME/install && make && make install && popd
  - pushd Bonmin/Bonmin && ./configure --prefix=$HOME/install && make && make install && popd
  - mkdir build
  - pushd build
  - export CFLAGS=""
  - export CXXFLAGS=""
  - if $VISHIDDEN ; then CFLAGS="$CFLAGS -fvisibility=hidden" ; fi
  - if $VISHIDDEN ; then CXXFLAGS="$CXXFLAGS -fvisibility=hidden" ; fi
  - export CFGFLAGS=""
  - if $ENABLEDEBUG ; then CFGFLAGS="$CFGFLAGS --enable-debug" ; fi
  - if ! $ENABLEDEBUG ; then CFLAGS="$CFLAGS -DNDEBUG" ; CXXFLAGS="$CXXFLAGS -DNDEBUG" ; fi
  - ../Couenne/configure --prefix=$HOME/install $CFGFLAGS
  - make
  - make test
  - make install
